workflow:
  rules:
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_COMMIT_MESSAGE =~ /^Update build version*/
      when: never
    - if: $CI_COMMIT_BRANCH

stages:
  - build
  - deploy

build_test_image:
  stage: build
  script:
    - docker build -t docker.infra.cloveri.com/profplay/frontend/vit.ru.profplay.test .
    - docker login https://docker.infra.cloveri.com -u $CI_REGISTRY_USER --password-stdin <<<$CI_JOB_TOKEN
    - docker push docker.infra.cloveri.com/profplay/frontend/vit.ru.profplay.test
  after_script:
    - docker rmi docker.infra.cloveri.com/profplay/frontend/vit.ru.profplay.test
  rules:
    - if: '$CI_COMMIT_BRANCH == "dev"'
  tags: [docker]

build_test_image:
  stage: build
  script:
    - docker build -t docker.infra.cloveri.com/profplay/frontend/vit.ru.profplay .
    - docker login https://docker.infra.cloveri.com -u $CI_REGISTRY_USER --password-stdin <<<$CI_JOB_TOKEN
    - docker push docker.infra.cloveri.com/profplay/frontend/vit.ru.profplay
  after_script:
    - docker rmi docker.infra.cloveri.com/profplay/frontend/vit.ru.profplay
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  tags: [docker]

deploy_in_test:
  stage: deploy
  script:
    - docker login https://docker.infra.cloveri.com -u $CI_REGISTRY_USER --password-stdin <<<$CI_JOB_TOKEN
    - docker pull docker.infra.cloveri.com/profplay/frontend/vit.ru.profplay.test
    - docker run -d -p 65530:80 --name vit.ru.profplay docker.infra.cloveri.com/profplay/frontend/vit.ru.profplay.test
    - sleep 15
    - docker logs vit.ru.profplay
  tags: [profplay]
